# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 18 Apr 2011 22:30:30 +0000
*               @ALL          1
*               @user         8
