<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Mon, 18 Apr 2011 22:30:30 +0000
 */
$conf['title'] = 'Francois Bayart Sandbox';
$conf['lang'] = 'en';
$conf['license'] = 'gnufdl';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
